from pathlib import Path
from app.core.models import BuildResult


class ProjectBuilder:
    """Deterministic project builder used by the UI and later AI agents."""

    def build_python_project(self, destination: Path, name: str) -> BuildResult:
        destination = Path(destination).resolve()
        project = destination / name
        if project.exists():
            return BuildResult(False, project, [], "Project already exists.")

        (project / "src").mkdir(parents=True)
        (project / "tests").mkdir()
        files = {
            "src/main.py": 'def main():\n    return "Hello from AutoFix"\n\nif __name__ == "__main__":\n    main()\n',
            "tests/test_main.py": 'from src.main import main\n\ndef test_main():\n    assert main() == "Hello from AutoFix"\n',
            "README.md": f"# {name}\n\nGenerated by AutoFix AI Studio.\n",
            "pyproject.toml": f'[project]\nname = "{name.lower().replace(" ", "-")}"\nversion = "0.1.0"\n',
        }
        created = []
        for relative, content in files.items():
            path = project / relative
            path.write_text(content, encoding="utf-8")
            created.append(path)
        return BuildResult(True, project, created, "Project generated successfully.")
